name: Test Staging CI

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  stage-core:
    uses: ./.github/workflows/reusable.yml
    with:
      include-jobs: >-
        [
          "ubuntu-22.04-x86_64-ninja-gcc-release",
          "ubuntu-22.04-armv8-ninja-gcc-release",
          "manylinux_2_28-x86_64-ninja-gcc-release",
          "windows-2022-x86_64-msvs-v143-release",
          "windows-2022-x86-msvs-v143-release",
          "macos-26-x86_64-ninja-appleclang-release",
          "macos-26-armv8-ninja-appleclang-release"
        ]
      cmake-presets: >-
        [
          {
            "match-jobs": ["*"],
            "configure-preset": "module-no-tests",
            "build-targets": ["hello-core"],
            "cache-variables": 
            {
              "OPENDAQ_PACKAGE_NAME_OVERRIDE": "hello-core"
            }
          }
        ]
      packages: >-
        [
          { "match-jobs": ["windows-*"], "choco-install": ["nsis"] }
        ]
      cpack-presets: >-
        [
          {
            "match-jobs": ["*"], 
            "enable-staging": true,
            "variables": 
            {
              "CPACK_ARCHIVE_COMPONENT_INSTALL": "ON", 
              "CPACK_COMPONENTS_ALL": "core"
            }
          },
          { "match-jobs": ["ubuntu-*"],  "package": "DEB",          "variables": { "CPACK_DEB_COMPONENT_INSTALL": "ON" } },
          { "match-jobs": ["windows-*"], "package": "NSIS" },
          { "match-jobs": ["macos-*"],   "package": "productbuild", "variables": { "CPACK_PRODUCTBUILD_COMPONENT_INSTALL": "ON" } }
        ]
      upload-pattern: core-*

  stage-module:
    needs: stage-core
    uses: ./.github/workflows/reusable.yml
    with:
      include-jobs: >-
        [
          "ubuntu-22.04-x86_64-ninja-gcc-release",
          "ubuntu-22.04-armv8-ninja-gcc-release",
          "manylinux_2_28-x86_64-ninja-gcc-release",
          "windows-2022-x86_64-msvs-v143-release",
          "windows-2022-x86-msvs-v143-release",
          "macos-26-x86_64-ninja-appleclang-release",
          "macos-26-armv8-ninja-appleclang-release"
        ]
      cmake-presets: >-
        [
          {
            "match-jobs": ["*"],
            "configure-preset": "module-no-tests",
            "cache-variables":
            {
              "HELLO_USE_INSTALLED_CORE": "ON",
              "CMAKE_PREFIX_PATH": "${sourceDir}/staging-deps",
              "OPENDAQ_PACKAGE_NAME_OVERRIDE": "hello-module"
            }
          }
        ]
      packages: >-
        [
          {
            "match-jobs": ["ubuntu-22.04-x86_64-*"],
            "artifacts": [{ "name": "core-staging-ubuntu-22.04-x86_64-*", "dir": "staging-deps" }]
          },
          {
            "match-jobs": ["ubuntu-22.04-armv8-*"],
            "artifacts": [{ "name": "core-staging-ubuntu-22.04-armv8-*", "dir": "staging-deps" }]
          },
          {
            "match-jobs": ["windows-2022-x86_64-*"],
            "choco-install": ["nsis"],
            "artifacts": [{ "name": "core-staging-windows-2022-x86_64-*", "dir": "staging-deps" }]
          },
          {
            "match-jobs": ["windows-2022-x86-*"],
            "choco-install": ["nsis"],
            "artifacts": [{ "name": "core-staging-windows-2022-x86-*", "dir": "staging-deps" }]
          },
          {
            "match-jobs": ["macos-26-x86_64-*"],
            "artifacts": [{ "name": "core-staging-macos-26-x86_64-*", "dir": "staging-deps" }]
          },
          {
            "match-jobs": ["macos-26-armv8-*"],
            "artifacts": [{ "name": "core-staging-macos-26-armv8-*", "dir": "staging-deps" }]
          },
          {
            "match-jobs": ["manylinux*"],
            "artifacts": [{ "name": "core-staging-manylinux*", "dir": "staging-deps" }]
          }
        ]
      cpack-presets: >-
        [
          {
            "match-jobs": ["*"],
            "enable-staging": true,
            "variables":
            {
              "CPACK_ARCHIVE_COMPONENT_INSTALL": "ON",
              "CPACK_COMPONENTS_ALL": "module"
            }
          },
          { "match-jobs": ["ubuntu-*"],  "package": "DEB",          "variables": { "CPACK_DEB_COMPONENT_INSTALL": "ON" } },
          { "match-jobs": ["windows-*"], "package": "NSIS" },
          { "match-jobs": ["macos-*"],   "package": "productbuild", "variables": { "CPACK_PRODUCTBUILD_COMPONENT_INSTALL": "ON" } }
        ]
      upload-pattern: module-*
